[build]
  publish   = "."                 # sajikan root repo
  functions = "netlify/functions" # folder functions

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# (opsional) CORS global
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
